Network Training
CSC207-2023Y-UofT/ai-playground pull request #24
Opened 2023-07-27 22:58 UTC by Rishit-dagli

This PR adds code to train the model.

Closes #2

2023-07-27 23:39 UTC, T3CHW1ZRD approved these changes

2023-07-27 23:39 UTC, T3CHW1ZRD commented on src/main/java/com/playground/playground/modelling/NeuralNet.java
good neural network implementation

2023-07-27 23:39 UTC, T3CHW1ZRD commented on src/main/java/com/playground/playground/modelling/ModelTrainingServices.java
looks good we may have to move the import dependencies to a higher layer later

2023-07-27 23:39 UTC, T3CHW1ZRD commented on build.gradle
looks good

2023-07-27 23:39 UTC, T3CHW1ZRD commented on .github/CODEOWNERS
yes

2023-07-27 23:42 UTC, Shivesh777 reviewed
Some checks seem to fail, do you mind addressing them and modifying the code to fix that?

2023-08-02 03:17 UTC, Shivesh777 reviewed
I do not see where the training metrics are being stored, is that being upon in a different branch?

2023-08-03 01:13 UTC, Ford-Robert requested changes
Could you add some javadocs to the main classes, and most important methods to increase the readability of this code. Especially for the classes/functions that will be called by Use-case and Driver layers. Specifically when the play button is pressed which method is called to initiate the training process, and where are the weights stored for line-thinkness (if we end up implementing that feature)

2023-08-03 02:35 UTC, Shivesh777 submitted a review, later dismissed

2023-08-03 02:37 UTC, Rishit-dagli commented
/hold because I need to still fix this PR, running a bit late on this one

2023-08-03 05:49 UTC, Rishit-dagli commented
/area modelling

2023-08-03 05:49 UTC, Rishit-dagli commented
/priority high

2023-08-03 05:55 UTC, Rishit-dagli commented
> Could you add some javadocs to the main classes, and most important methods to increase the readability of this code

Ah, yes I need to do it for all methods, considering the time crunch we have and are yet to integrate this, I was thinking maybe I could do it but defer it to another PR as of now, what do you think?

> Specifically when the play button is pressed which method is called to initiate the training process, and where are the weights stored for line-thinkness (if we end up implementing that feature)

This is still WIP, working on those aspects yet, this is currently just the training code and nothing more.

2023-08-03 07:26 UTC, Rishit-dagli commented
This PR is now ready for review

2023-08-03 16:37 UTC, Ford-Robert approved these changes

2023-08-03 16:50 UTC, Rishit-dagli commented
/retitle Building and training the Neural Net

2023-08-03 17:01 UTC, Shivesh777 approved these changes

2023-08-03 17:01 UTC, merged