Feature 12 choose features
CSC207-2023Y-UofT/ai-playground pull request #27
Opened 2023-07-27 23:26 UTC by Ford-Robert

This feature handles choosing 'features'. In this case 'features' are transformations applied to the dataset before training. For example the X^2 feature squares all of the x values for both datasets, while leaving the y values the same. This feature is responsible for collecting which features and the noise selected by the users, then creating a new dataset using GenerateDataset and applying the necessary transforms and noise.

2023-07-28 05:01 UTC, snkrs23 requested changes
Please make sure they pass auto-grading before requesting a pull.

2023-08-01 20:29 UTC, snkrs23 approved these changes
Everything looks good to me. The changes you made fix the problems you've had!

2023-08-01 21:19 UTC, alvina-yang commented on src/main/java/FeatureController.java
Maybe you can also add some error handling in the switch-case statements so that the program doesn't silently fail

2023-08-01 21:19 UTC, alvina-yang commented on src/main/java/GenerateDatasets.java
There's some code duplication in the adding noise section of some of the methods. Maybe consider adding a utility method?

2023-08-01 21:26 UTC, snkrs23 commented on src/main/java/GenerateDatasets.java
I agree with Alvina here, perhaps think of just having one method for sinVal and squareVal and just call that method with the appropriate parameters when needed. But if that does not work, then this is the most correct implementation.

2023-08-01 21:28 UTC, snkrs23 commented on src/main/java/FeatureController.java
Error handling can be done in the UI since the UI makes the calls to FeatureController, Features, and GenerateDatasets and should not send in illogical inputs.

2023-08-01 22:18 UTC, Ford-Robert commented on src/main/java/GenerateDatasets.java
sinVal and squareVal are each individual methods and the switch statements determine which input needs to be added, where 0 is X and 1 is Y.

2023-08-01 22:19 UTC, Ford-Robert commented on src/main/java/GenerateDatasets.java
Oh yeah GenerateDatasets was not written by me i dont know why its included in this pr

2023-08-01 22:22 UTC, Ford-Robert commented on src/main/java/FeatureController.java
I think its unlikely for illegal arguments to be passed through these functions but ill add default cases for debugging purposes

2023-08-01 22:40 UTC, Ford-Robert commented
Resolves #13

2023-08-01 23:16 UTC, Rishit-dagli commented
\hold until we merge #25

2023-08-03 02:35 UTC, Shivesh777 submitted a review, later dismissed

2023-08-03 05:59 UTC, Rishit-dagli commented
/area datasets

2023-08-03 16:07 UTC, Rishit-dagli commented
/unhold now that #25 is merged

2023-08-03 16:08 UTC, Rishit-dagli commented
@Ford-Robert Do you need any help resolving merge conflicts

2023-08-03 16:47 UTC, Rishit-dagli submitted a review, later dismissed
Looks good /lgtm

2023-08-03 16:47 UTC, Rishit-dagli approved these changes
Looks good /lgtm

2023-08-03 16:49 UTC, Rishit-dagli commented
/cc Shivesh777

2023-08-03 16:49 UTC, Rishit-dagli commented
/retitle Add ability to Transform Features

2023-08-03 16:52 UTC, Rishit-dagli commented
/unhold now that https://github.com/CSC207-2023Y-UofT/ai-playground/pull/25 is merged

2023-08-03 16:55 UTC, Rishit-dagli submitted a review, later dismissed
For some reason my review got invalidated again. /lgtm

2023-08-03 17:02 UTC, Shivesh777 approved these changes

2023-08-03 17:51 UTC, Shivesh777 approved these changes

2023-08-03 18:32 UTC, Shivesh777 approved these changes

2023-08-03 18:40 UTC, Shivesh777 approved these changes

2023-08-03 18:50 UTC, Rishit-dagli approved these changes
/lgtm

2023-08-03 18:50 UTC, merged